### ISSUE TITLE
Thank you for your help

### ISSUE THREAD

**Issue by Nullaha** [ungarj/label_centerlines#11]
Thank you very much.
At first, my goal is to do an automatic calculation of the length of the glacier.
I was amazed when I saw your code on gihub and it inspired me.
So thank you.
I want to end with a question.
In the looking for the path step, whether it can be based on both the distance weight and the altitude value.
Thus, the path with the shortest cutting distance from low altitude to high altitude is obtained?

**Comment by ungarj** [comment]
Hi @Nullaha!

The tool creates a `networkx.Graph` in between so what you can do is to start from [here](https://github.com/ungarj/label_centerlines/blob/master/label_centerlines/_src.py#L69) and use one of the graph functions to do whatever you need to do with the graph: https://networkx.github.io/documentation/stable/reference/index.html

When reading the elevation values you can use `rasterio` and its `sample()` function to get the elevation value over a certain point: https://rasterio.readthedocs.io/en/latest/api/rasterio._io.html#rasterio._io.DatasetReaderBase.sample

**Comment by Nullaha** [comment]
Ok, thank you @ungari!
i will keep trying.
