### ISSUE TITLE
Allow setting of maxnum longest paths

### ISSUE THREAD

**Issue by geographika** [ungarj/label_centerlines#5]
Thanks for a great project!
I've been trying it out for creating road centre lines from polygons. One issue I've run into is I had to always use the longest path, rather than select the smoothest from the top 5 longest. 

With the top 5 I only get a short section (pink lines are the Voronoi lines, grey/blue line the output centre line):

![center_line_max_5](https://user-images.githubusercontent.com/490840/38856952-3e8bf668-4228-11e8-8ce3-ab1de077719a.png)

When selecting just the longest (with ``_get_longest_paths(nodes, graph, maxnum=1)`` I get the full line:

![center_line_longest](https://user-images.githubusercontent.com/490840/38856967-48d1bbd0-4228-11e8-8dc1-bf427c26a018.png)

Polygon WKT is:

```language wkt
POLYGON ((518523.664 730722.779, 518519.335 730721.311, 518515.476 730720.002, 518517.91 730718.394, 518517.63 730711.824, 518519.123 730703.743, 518520.338 730689.848, 518516.265 730680.265, 518511.185 730671.948, 518498.973 730657.294, 518505.454 730646.656, 518506.612 730644.308, 518507.298 730642.9179999999, 518509.05 730645.093, 518510.342 730646.697, 518508.092 730653.775, 518509.626 730659.326, 518521.801 730674.1850000001, 518529.156 730683, 518527.916 730689.823, 518527.416 730691.5919999999, 518526.166 730695.384, 518525.914 730697.615, 518524.193 730709.558, 518524.231 730710.348, 518523.529 730715.078, 518522.777 730719.711, 518522.996 730721.355, 518523.664 730722.779))
```
I used the following settings:

`get_centerline(poly, segmentize_maxlen=0.5, max_points=3000, simplification=0.05, smooth_sigma=1)
`

I can create a pull request if you think adding a `maxpaths `property is appropriate.

**Comment by ungarj** [comment]
Sure, I also thought that making a hard coded limit to the 5 longest paths is a bit arbitrary but I didn't need it so far.

A PR would be great! Could you also add a ``maxpaths`` parameter to the CLI?

**Comment by svenjr** [comment]
Has this been implemented?

**Comment by ungarj** [comment]
So far to my knowledge it has not been implemented yet.

@geographika, do you need any help or guidance for a PR?
