### ISSUE TITLE
libgfortran error

### ISSUE THREAD

**Issue by eigenwillig** [ungarj/label_centerlines#6]
I've got the following error:

`ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory`

After recompiling numpy there is only

`ImportError: /usr/lib/python3.6/site-packages/numpy/random/mtrand.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZGVbN2v___log_finite`

(related to https://github.com/JohannesBuchner/cuba/issues/1 ?)

--

Sorry for this bug report, it seems related to my distro's numpy installation.

**Comment by ungarj** [comment]
Closing issue as it seems to be not directly related to this library.
